---
title: "PEC2_Visualizacion"
author: "Manuel Navarro Sicre"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(flexdashboard)
library(viridis)
library(dplyr)
library(readr)
```

## Ejercicio 1: Scatter plot
```{r}
ggplot(mtcars, aes(x = wt, y = mpg, color = factor(cyl))) +
geom_point(size = 3) +
labs(
title = "Relación entre el peso del vehículo y el consumo de combustible",
subtitle = "Datos del dataset mtcars",
x = "Peso del vehículo (miles de libras)",
y = "Millas por galón (mpg)",
color = "Cilindros"
) +
theme_minimal()
```

## Ejercicio 2: Gauge diagram
```{r}
data <- read_csv("share-electricity-renewables/share-electricity-renewables.csv")

espana <- subset(data, Entity == "Spain" & Year == 2023)
valor <- espana$`Renewables - % electricity`

gauge(valor,
min = 0, max = 100, symbol = "%",
label = "Electricidad renovable (España, 2023)",
gaugeSectors(
success = c(60, 100),
warning = c(30, 59),
danger = c(0, 29)
))
```

## Ejercicio 3: Hexagon Binning
```{r}
data <- read_csv("co2-data-master/owid-co2-data.csv")

df <- data %>%
  filter(!is.na(co2_per_capita), !is.na(gdp), !is.na(population)) %>%
  mutate(gdp_per_capita = gdp / population) %>%
  filter(co2_per_capita > 0, gdp_per_capita > 0) %>%  # <-- Añadido
  select(country, year, co2_per_capita, gdp_per_capita)

ggplot(df, aes(x = gdp_per_capita, y = co2_per_capita)) +
geom_hex() +
scale_fill_viridis_c(option = "plasma") +
scale_x_log10() +
scale_y_log10() +
labs(
title = "Relación entre PIB per cápita y emisiones de CO₂ per cápita",
subtitle = "Datos de Our World in Data",
x = "PIB per cápita (log)",
y = "Emisiones de CO₂ per cápita (log)",
fill = "Densidad"
) +
theme_minimal()
```